services:
  postgres:
    image: 'postgres:latest'
    restart: always
    container_name: postgres-db
    environment:
      - 'POSTGRES_DB=anti_corruption_department'
      - 'POSTGRES_PASSWORD=secret_user_passwd'
      - 'POSTGRES_USER=postgres_user'
    ports:
      - '5432:5432'
